name: Pull upstream
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  pull-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Keep cron active
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1
      - name: Pull upstream
        run: |
          ./download.sh
          git config user.name ci
          git config user.email ci@openbible.io
          git add .
          git diff-index --cached --quiet HEAD || git commit -m "update $(date)"
          git push origin master
