name: Pull upstream
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  actions: write

jobs:
  pull-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Keep cron active
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Pull upstream
        run: |
          bun download
          bun convert
          git config user.name ci
          git config user.email ci@openbible.io
          git add .
          if git diff-index --cached --quiet HEAD ; then
            echo "No changes"
          else
            git commit -m "automatic update"
            git push origin master
            bun pm version patch
            git add .
            git commit -m "version bump"
            bun publish --access public
          fi
